/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarsHistory;

/**
 *
 * @author rakeshbaddi
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    
    CarsHistory history;

    public UpdateJPanel(CarsHistory history) {
        initComponents();
        this.history = history;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AvailGroup = new javax.swing.ButtonGroup();
        CertGroup = new javax.swing.ButtonGroup();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCars = new javax.swing.JTable();
        labelSerial = new javax.swing.JLabel();
        labelErr2 = new javax.swing.JLabel();
        labelBrand1 = new javax.swing.JLabel();
        labelErr6 = new javax.swing.JLabel();
        labelErr1 = new javax.swing.JLabel();
        textSerial = new javax.swing.JTextField();
        radioButtonCertYes = new javax.swing.JRadioButton();
        radioButtonCertNo = new javax.swing.JRadioButton();
        textSeats = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelErr4 = new javax.swing.JLabel();
        labelErr5 = new javax.swing.JLabel();
        textCity = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        labelErr3 = new javax.swing.JLabel();
        labelYear = new javax.swing.JLabel();
        radioButtonAvailNo = new javax.swing.JRadioButton();
        textYear = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        textBrand = new javax.swing.JTextField();
        labelBrand = new javax.swing.JLabel();
        labelSeats = new javax.swing.JLabel();
        radioButtonAvailYes = new javax.swing.JRadioButton();
        labelAvailability = new javax.swing.JLabel();
        labelCertificate = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        labelAvailableIn = new javax.swing.JLabel();
        textAvailableIn = new javax.swing.JTextField();
        labelErr7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        labelTitle.setBackground(new java.awt.Color(153, 204, 255));
        labelTitle.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("VIEW/UPDATE CARS");

        tableCars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        tableCars.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Brand", "Model Name", "City", "Availability", "No. of Seats", "Manufacturing Year", "Serial Number", "Maintenance Certificate", "Available In (Minutes)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCars.setShowGrid(true);
        jScrollPane1.setViewportView(tableCars);

        labelSerial.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelSerial.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelSerial.setText("Serial No :");

        labelErr2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelErr2.setForeground(java.awt.Color.red);

        labelBrand1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelBrand1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelBrand1.setText("City :");

        labelErr6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelErr6.setForeground(java.awt.Color.red);

        labelErr1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelErr1.setForeground(java.awt.Color.red);

        textSerial.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textSerial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        textSerial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSerialFocusLost(evt);
            }
        });
        textSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSerialActionPerformed(evt);
            }
        });

        CertGroup.add(radioButtonCertYes);
        radioButtonCertYes.setText("Yes");
        radioButtonCertYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCertYesActionPerformed(evt);
            }
        });

        CertGroup.add(radioButtonCertNo);
        radioButtonCertNo.setText("No");
        radioButtonCertNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCertNoActionPerformed(evt);
            }
        });

        textSeats.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textSeats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        textSeats.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textSeatsFocusLost(evt);
            }
        });
        textSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSeatsActionPerformed(evt);
            }
        });

        labelName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelName.setText("Model Name :");

        labelErr4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelErr4.setForeground(java.awt.Color.red);

        labelErr5.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelErr5.setForeground(java.awt.Color.red);

        textCity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textCity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        textCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCityFocusLost(evt);
            }
        });
        textCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCityActionPerformed(evt);
            }
        });

        textName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        textName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNameFocusLost(evt);
            }
        });
        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        labelErr3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelErr3.setForeground(java.awt.Color.red);

        labelYear.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelYear.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelYear.setText("Manufacturing Year :");

        AvailGroup.add(radioButtonAvailNo);
        radioButtonAvailNo.setText("No");
        radioButtonAvailNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAvailNoActionPerformed(evt);
            }
        });

        textYear.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        textYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textYearFocusLost(evt);
            }
        });
        textYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textYearActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 204, 255));
        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        textBrand.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textBrand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        textBrand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textBrandFocusLost(evt);
            }
        });
        textBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBrandActionPerformed(evt);
            }
        });

        labelBrand.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelBrand.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelBrand.setText("Car Brand :");

        labelSeats.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelSeats.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelSeats.setText("No. of Seats :");

        AvailGroup.add(radioButtonAvailYes);
        radioButtonAvailYes.setText("Yes");
        radioButtonAvailYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAvailYesActionPerformed(evt);
            }
        });

        labelAvailability.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelAvailability.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelAvailability.setText("Availability :");

        labelCertificate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelCertificate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelCertificate.setText("Maintenance Certificate :");

        btnView.setBackground(new java.awt.Color(153, 204, 255));
        btnView.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 204, 255));
        btnDelete.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labelAvailableIn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelAvailableIn.setText("Available In (Minutes) :");

        textAvailableIn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        textAvailableIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        textAvailableIn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textAvailableInFocusLost(evt);
            }
        });

        labelErr7.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelErr7.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSerial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelBrand1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAvailableIn))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelErr7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textAvailableIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textYear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioButtonAvailYes)
                                .addGap(18, 18, 18)
                                .addComponent(radioButtonAvailNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioButtonCertYes)
                                .addGap(18, 18, 18)
                                .addComponent(radioButtonCertNo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelErr6)
                                    .addComponent(labelErr5)
                                    .addComponent(labelErr4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelErr3)
                                    .addComponent(labelErr2)
                                    .addComponent(labelErr1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(labelTitle)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelBrand)
                        .addComponent(textBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(labelErr1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(labelErr2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBrand1)
                    .addComponent(textCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(labelErr3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAvailability)
                    .addComponent(radioButtonAvailYes)
                    .addComponent(radioButtonAvailNo))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(labelErr4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(labelErr5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSerial)
                    .addComponent(textSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(labelErr6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonCertYes)
                        .addComponent(radioButtonCertNo))
                    .addComponent(labelCertificate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAvailableIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAvailableIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErr7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textSerialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSerialFocusLost
        // TODO add your handling code here:
        validateLength(textSerial, labelErr6, "Serial Number");
        
        if(history.getHistory().size()>0) {
            for(Car car : history.getHistory()) {
                if(textSerial.getText().equalsIgnoreCase(car.getSerialNumber())) {
                    labelErr6.setText("Serial Number has to be unique");
                }
            }
        }
    }//GEN-LAST:event_textSerialFocusLost

    private void textSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSerialActionPerformed

    private void radioButtonCertYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCertYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonCertYesActionPerformed

    private void radioButtonCertNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCertNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonCertNoActionPerformed

    private void textSeatsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSeatsFocusLost
        // TODO add your handling code here:
        validateSeats(textSeats);
    }//GEN-LAST:event_textSeatsFocusLost

    private void textSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSeatsActionPerformed

    private void textCityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCityFocusLost
        // TODO add your handling code here:
        validateLength(textCity, labelErr3, "City");
    }//GEN-LAST:event_textCityFocusLost

    private void textCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCityActionPerformed

    private void textNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNameFocusLost
        // TODO add your handling code here:
        validateLength(textName, labelErr2, "Model Name");
    }//GEN-LAST:event_textNameFocusLost

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void radioButtonAvailNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAvailNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAvailNoActionPerformed

    private void textYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textYearFocusLost
        // TODO add your handling code here:
        validateYear(textYear);
    }//GEN-LAST:event_textYearFocusLost

    private void textYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textYearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        if(!textBrand.getText().isBlank() && !textName.getText().isBlank() && !textCity.getText().isBlank() && !textSeats.getText().isBlank() && 
            !textYear.getText().isBlank() && !textSerial.getText().isBlank() && !textAvailableIn.getText().isBlank()) {

            String brand = textBrand.getText();
            String name = textName.getText();
            String city = textCity.getText();
            String availability = radioButtonSelection(radioButtonAvailYes, radioButtonAvailNo, AvailGroup);
            int seats = Integer.parseInt(textSeats.getText());
            int year = Integer.parseInt(textYear.getText());
            String serial = textSerial.getText();
            String certificate = radioButtonSelection(radioButtonCertYes, radioButtonCertNo, CertGroup);
            int availableIn = Integer.parseInt(textAvailableIn.getText());
            

            Car car = history.updateCar(tableCars.getSelectedRow());
            car.setBrand(brand);
            car.setModelName(name);
            car.setCity(city);
            car.setAvailability(availability);
            car.setSeats(seats);
            car.setYear(year);
            car.setSerialNumber(serial);
            car.setCertificate(certificate);
            car.setAvailableIn(availableIn);

            JOptionPane.showMessageDialog(this, "Car details updated succesfully");
            populateTable();

            textBrand.setText("");
            textName.setText("");
            textCity.setText("");
            textSeats.setText("");
            textYear.setText("");
            textSerial.setText("");
            textAvailableIn.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Please enter valid details");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void textBrandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textBrandFocusLost
        // TODO add your handling code here:
        validateLength(textBrand, labelErr1, "Brand");
    }//GEN-LAST:event_textBrandFocusLost

    private void textBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBrandActionPerformed

    private void radioButtonAvailYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAvailYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonAvailYesActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tableCars.getSelectedRow();
        
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tableCars.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
        
        history.deleteCar(selectedCar);
        JOptionPane.showMessageDialog(this, "Car details deleted succesfully");
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tableCars.getSelectedRow();
        
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tableCars.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
        
        textBrand.setText(selectedCar.getBrand());
        textName.setText(selectedCar.getModelName());
        textCity.setText(selectedCar.getCity());
        
        if(selectedCar.getAvailability().equals("Yes")) {
            radioButtonAvailYes.setSelected(true);
        } else {
            radioButtonAvailNo.setSelected(true);
        }
        
        textSeats.setText(String.valueOf(selectedCar.getSeats()));
        textYear.setText(String.valueOf(selectedCar.getYear()));
        textSerial.setText(selectedCar.getSerialNumber());
        
        if(selectedCar.getCertificate().equals("Yes")) {
            radioButtonCertYes.setSelected(true);
        } else {
            radioButtonCertNo.setSelected(true);
        }
        
        textAvailableIn.setText(String.valueOf(selectedCar.getAvailableIn()));   
    }//GEN-LAST:event_btnViewActionPerformed

    private void textAvailableInFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textAvailableInFocusLost
        // TODO add your handling code here:
        validateAvailableIn(textAvailableIn);
    }//GEN-LAST:event_textAvailableInFocusLost

    public String radioButtonSelection(JRadioButton btnYes, JRadioButton btnNo, ButtonGroup btnGroup) {
        btnYes.setActionCommand("Yes");
        btnNo.setActionCommand("No");
        
        return btnGroup.getSelection().getActionCommand();
    }
    
    private void validateLength(JTextField textField, JLabel label, String msg) {
        if(textField.getText().isBlank()) {
            label.setText("Enter Valid " + msg);
        } else {
            label.setText("");
        }
    }
    
    private void validateSeats(JTextField textField) {
        if(!textField.getText().matches("[1-9]")) {
            labelErr4.setText("Enter Valid Number between 1 to 9");
        } else {
            labelErr4.setText("");
        }
    }
    
    private void validateYear(JTextField textField) {
        if(!textField.getText().matches("\\d{4}")) {
            labelErr5.setText("Enter Valid Year");
        } else {
            labelErr5.setText("");
        }
        
        if(Integer.parseInt(textField.getText())>2021) {
            labelErr5.setText("Year cannot be greater than 2021");
        }
    }
    
    private void validateAvailableIn(JTextField textField) {
        if(!textField.getText().matches("\\d+")) {
            labelErr7.setText("Enter Valid Number");
        } else {
            labelErr7.setText("");
        }
        
        if(Integer.parseInt(textField.getText())<0) {
            labelErr7.setText("Available In cannot be less than 0");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AvailGroup;
    private javax.swing.ButtonGroup CertGroup;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAvailability;
    private javax.swing.JLabel labelAvailableIn;
    private javax.swing.JLabel labelBrand;
    private javax.swing.JLabel labelBrand1;
    private javax.swing.JLabel labelCertificate;
    private javax.swing.JLabel labelErr1;
    private javax.swing.JLabel labelErr2;
    private javax.swing.JLabel labelErr3;
    private javax.swing.JLabel labelErr4;
    private javax.swing.JLabel labelErr5;
    private javax.swing.JLabel labelErr6;
    private javax.swing.JLabel labelErr7;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSeats;
    private javax.swing.JLabel labelSerial;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelYear;
    private javax.swing.JRadioButton radioButtonAvailNo;
    private javax.swing.JRadioButton radioButtonAvailYes;
    private javax.swing.JRadioButton radioButtonCertNo;
    private javax.swing.JRadioButton radioButtonCertYes;
    private javax.swing.JTable tableCars;
    private javax.swing.JTextField textAvailableIn;
    private javax.swing.JTextField textBrand;
    private javax.swing.JTextField textCity;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textSeats;
    private javax.swing.JTextField textSerial;
    private javax.swing.JTextField textYear;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tableCars.getModel();
        model.setRowCount(0);
        
        for(Car car : history.getHistory()) {
            
            Object[] row = new Object[9];
            row[0] = car;
            row[1] = car.getModelName();
            row[2] = car.getCity();
            row[3] = car.getAvailability();
            row[4] = car.getSeats();
            row[5] = car.getYear();
            row[6] = car.getSerialNumber();
            row[7] = car.getCertificate();
            row[8] = car.getAvailableIn();
            
            model.addRow(row);
        }
    }
}
